"""Semantic validation helpers for inverse-design config step 9.1 item 4."""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Literal, Tuple

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from PhotonicsAI.Photon.tidy3d_runner import (
    _default_source_direction_for_port,
    _port_prop_axis,
    monitor_size_for_port,
)
from PhotonicsAI.tools.inverse_design_config import (
    InverseDesignConfigBundle,
    format_config_validation_error,
    parse_inverse_design_config,
)
from PhotonicsAI.tools.inverse_design_rag_memory import Step4ConstraintPacket
from PhotonicsAI.tools.inverse_design_working_memory import (
    InverseDesignWorkingMemory,
    get_inverse_design_working_memory,
)

_ALLOWED_BOUNDARY_TYPES = {"pml", "periodic", "pec", "pmc"}
_METRIC_GOAL_COMPATIBILITY = {
    "transmission": "maximize",
    "efficiency": "maximize",
    "bandwidth": "maximize",
    "q_factor": "maximize",
    "extinction_ratio": "maximize",
    "loss": "minimize",
    "insertion_loss": "minimize",
    "reflection": "minimize",
    "crosstalk": "minimize",
}
_LIGHT_SPEED_M_PER_S = 299_792_458.0
_MIN_STEPS_PER_WAVELENGTH_RECOMMENDED = 10
_DEFAULT_GROUP_INDEX = 4.0
_MAX_SHUTOFF_FOR_ACCURACY = 1e-3
LLMCallFn = Any


class StrictModel(BaseModel):
    """Base model that rejects unknown fields to keep output machine-readable."""

    model_config = ConfigDict(extra="forbid")


class ValidationIssue(StrictModel):
    """Single validation issue with a deterministic location and fix hint."""

    code: str
    path: str
    message: str
    severity: Literal["error", "warning"] = "error"


class RepairAction(StrictModel):
    """Machine-applicable repair action generated by the validator."""

    action: Literal["set_value", "add_item", "remove_item"]
    path: str
    value: Any = None
    reason: str


class ConfigValidationResult(StrictModel):
    """Validation result for step 9.1 item 4 acceptance."""

    ok: bool
    issues: List[ValidationIssue] = Field(default_factory=list)
    repair_actions: List[RepairAction] = Field(default_factory=list)
    review_notes: List[str] = Field(default_factory=list)
    review_repair_actions: List[RepairAction] = Field(default_factory=list)


class LLMReviewResult(StrictModel):
    """Optional non-blocking reviewer output for Step4 semantic enhancement."""

    review_notes: List[str] = Field(default_factory=list)
    repair_actions: List[RepairAction] = Field(default_factory=list)


def validate_config(
    payload: InverseDesignConfigBundle | Dict[str, Any],
    *,
    include_llm_review: bool | None = None,
    llm_call_fn: LLMCallFn | None = None,
    llm_model: str = "gpt-5.4",
    constraint_packet: Step4ConstraintPacket | Dict[str, Any] | None = None,
    memory_store: InverseDesignWorkingMemory | None = None,
    search_fn: Any | None = None,
    fetch_fn: Any | None = None,
) -> ConfigValidationResult:
    """Validate schema + semantic consistency and return executable repair actions."""

    memory = memory_store or get_inverse_design_working_memory()

    try:
        bundle = payload if isinstance(payload, InverseDesignConfigBundle) else parse_inverse_design_config(payload)
    except ValidationError as exc:
        summary = format_config_validation_error(exc)
        memory.record(
            stage="step4_validation",
            key="schema",
            summary="Step4 schema validation failed before semantic checks.",
            issues=[summary],
            proposed_fixes=["regenerate_with_inverse_design_config_schema"],
        )
        return ConfigValidationResult(
            ok=False,
            issues=[
                ValidationIssue(
                    code="schema_validation_failed",
                    path="root",
                    message=summary,
                    severity="error",
                )
            ],
            repair_actions=[
                RepairAction(
                    action="set_value",
                    path="root",
                    value="regenerate_with_inverse_design_config_schema",
                    reason="Payload violates required schema fields and must be regenerated.",
                )
            ],
        )

    issues: List[ValidationIssue] = []
    repair_actions: List[RepairAction] = []
    rag_packet = _coerce_constraint_packet(constraint_packet)

    _validate_source_and_domain(bundle, issues, repair_actions)
    _validate_monitors(bundle, issues, repair_actions)
    _validate_boundary(bundle, issues, repair_actions)
    _validate_optimization_variables(bundle, issues, repair_actions)
    _validate_metric_goal_consistency(bundle, issues, repair_actions)
    _validate_geometry_semantics(bundle, issues, repair_actions)
    _validate_source_monitor_semantics(bundle, issues, repair_actions)
    _validate_device_topology_priors(bundle, issues, repair_actions)
    _validate_mesh_and_spectral_semantics(bundle, issues, repair_actions)
    if rag_packet is not None:
        _validate_rag_constraint_packet(bundle, rag_packet, issues, repair_actions)
        memory.record(
            stage="step4_rag",
            key=bundle.simulation_config.component_type,
            summary="Step4 applied RAG constraint packet for semantic and hard-constraint checks.",
            evidence_urls=list(rag_packet.evidence_urls),
            metadata={
                "required_boundary": rag_packet.required_boundary,
                "required_monitor_types": rag_packet.required_monitor_types,
                "min_steps_per_wvl": rag_packet.min_steps_per_wvl,
            },
        )

    memory.record(
        stage="step4_validation",
        key=bundle.simulation_config.component_type,
        summary=(
            f"Step4 deterministic validation finished with {len(issues)} issues and "
            f"{len(repair_actions)} repair actions."
        ),
        issues=[issue.code for issue in issues],
        proposed_fixes=[action.path for action in repair_actions],
        metadata={
            "objective_metric": bundle.optimization_config.objective.metric,
            "objective_goal": bundle.optimization_config.objective.goal,
        },
    )

    review_notes: List[str] = []
    review_repair_actions: List[RepairAction] = []
    if _review_enabled(include_llm_review):
        review = _run_non_blocking_llm_review(
            bundle,
            deterministic_issues=issues,
            deterministic_actions=repair_actions,
            constraint_packet=rag_packet,
            llm_call_fn=llm_call_fn,
            llm_model=llm_model,
            memory_store=memory,
            search_fn=search_fn,
            fetch_fn=fetch_fn,
        )
        review_notes = list(review.review_notes)
        review_repair_actions = list(review.repair_actions)

    return ConfigValidationResult(
        ok=not any(iss.severity == "error" for iss in issues),
        issues=issues,
        repair_actions=repair_actions,
        review_notes=review_notes,
        review_repair_actions=review_repair_actions,
    )


def inverse_design_config_validation_schema() -> Dict[str, Any]:
    """Return schema for validator output."""

    return ConfigValidationResult.model_json_schema()


def _validate_source_and_domain(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    source = sim_cfg.source
    domain = sim_cfg.domain

    if abs(source.wavelength_nm - sim_cfg.wavelength_nm) > 1e-6:
        issues.append(
            ValidationIssue(
                code="source_wavelength_mismatch",
                path="simulation_config.source.wavelength_nm",
                message="Source wavelength must match simulation wavelength.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.source.wavelength_nm",
                value=sim_cfg.wavelength_nm,
                reason="Align source wavelength with simulation wavelength.",
            )
        )

    bounds = _domain_bounds(domain.size_um, domain.center_um)
    if not _point_within_bounds(source.center_um, bounds):
        safe_center = _clamp_point(source.center_um, bounds)
        issues.append(
            ValidationIssue(
                code="source_out_of_domain",
                path="simulation_config.source.center_um",
                message="Source center must lie within simulation domain.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.source.center_um",
                value=safe_center,
                reason="Move source center inside domain bounds.",
            )
        )


def _validate_monitors(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    monitors = sim_cfg.monitors

    has_flux = any(m.monitor_type == "flux" for m in monitors)
    has_mode = any(m.monitor_type == "mode" for m in monitors)
    if not has_flux:
        default_flux = {
            "name": "through_flux",
            "monitor_type": "flux",
            "center_um": [sim_cfg.domain.size_um[0] / 2 - 1.0, 0.0, 0.11],
            "size_um": [0.0, 1.5, 1.0],
            "freqs_hz": [_freq_from_wavelength_nm(sim_cfg.wavelength_nm)],
            "metric": "transmission",
        }
        issues.append(
            ValidationIssue(
                code="missing_flux_monitor",
                path="simulation_config.monitors",
                message="At least one flux monitor is required for objective evaluation.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="add_item",
                path="simulation_config.monitors",
                value=default_flux,
                reason="Add default output flux monitor for score extraction.",
            )
        )

    if not has_mode:
        default_mode = {
            "name": "mode_monitor",
            "monitor_type": "mode",
            "center_um": [sim_cfg.domain.size_um[0] / 2 - 1.0, 0.0, 0.11],
            "size_um": [0.0, 1.5, 1.0],
            "freqs_hz": [_freq_from_wavelength_nm(sim_cfg.wavelength_nm)],
            "metric": "mode_overlap",
        }
        issues.append(
            ValidationIssue(
                code="missing_mode_monitor",
                path="simulation_config.monitors",
                message="Mode monitor is recommended for robust optimization diagnostics.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="add_item",
                path="simulation_config.monitors",
                value=default_mode,
                reason="Add mode-overlap monitor to improve optimizer feedback.",
            )
        )

    bounds = _domain_bounds(sim_cfg.domain.size_um, sim_cfg.domain.center_um)
    component_type = getattr(sim_cfg, "component_type", "waveguide") or "waveguide"
    for idx, monitor in enumerate(monitors):
        if not _point_within_bounds(monitor.center_um, bounds):
            safe_center = _clamp_point(monitor.center_um, bounds)
            issues.append(
                ValidationIssue(
                    code="monitor_out_of_domain",
                    path=f"simulation_config.monitors.{idx}.center_um",
                    message="Monitor center must lie within simulation domain.",
                )
            )
            repair_actions.append(
                RepairAction(
                    action="set_value",
                    path=f"simulation_config.monitors.{idx}.center_um",
                    value=safe_center,
                    reason="Move monitor center inside domain bounds.",
                )
            )

        # Orientation check: flux / mode monitors must have exactly one
        # zero‑dimension in size_um (the propagation direction), AND the
        # zero must be on the correct axis for the monitor's port.
        if monitor.monitor_type in {"flux", "mode"}:
            # Extract port name from monitor name for accurate axis lookup.
            _port_match = re.search(r"(port_[oi]\d+)", monitor.name)
            inferred_port = _port_match.group(1) if _port_match else None
            wg_w = float(sim_cfg.geometry.parameters.get("wg_width", 0.5))
            wg_h = float(sim_cfg.geometry.parameters.get("wg_height", 0.22))

            zero_indices = [i for i, v in enumerate(monitor.size_um) if abs(v) < 1e-12]
            zero_count = len(zero_indices)

            # Case 1: wrong number of zero dimensions (0 or 2+)
            if zero_count != 1:
                # For auto-repair, if port is known use its axis; else default "x".
                repair_axis = _port_prop_axis(component_type, inferred_port or "port_o2")
                correct_size = list(monitor_size_for_port(repair_axis, wg_w, wg_h))
                issues.append(
                    ValidationIssue(
                        code="monitor_bad_orientation",
                        path=f"simulation_config.monitors.{idx}.size_um",
                        message=(
                            f"Flux/mode monitor '{monitor.name}' must have exactly "
                            f"one zero-dimension in size_um (current: {monitor.size_um})."
                        ),
                    )
                )
                repair_actions.append(
                    RepairAction(
                        action="set_value",
                        path=f"simulation_config.monitors.{idx}.size_um",
                        value=correct_size,
                        reason="Fix monitor orientation to be perpendicular to propagation axis.",
                    )
                )
            elif inferred_port is not None:
                # Case 2: exactly 1 zero, and port is known — verify the
                # zero is on the correct axis.
                # For axis="x" the zero must be at index 0; for "y" at index 1.
                axis = _port_prop_axis(component_type, inferred_port)
                expected_zero_idx = 0 if axis == "x" else 1
                if zero_indices[0] != expected_zero_idx:
                    correct_size = list(monitor_size_for_port(axis, wg_w, wg_h))
                    issues.append(
                        ValidationIssue(
                            code="monitor_wrong_zero_axis",
                            path=f"simulation_config.monitors.{idx}.size_um",
                            message=(
                                f"Flux/mode monitor '{monitor.name}' has zero on "
                                f"{'xyz'[zero_indices[0]]}-axis but {inferred_port} "
                                f"propagates along {axis}-axis — zero should be on "
                                f"{axis}-axis (index {expected_zero_idx})."
                            ),
                        )
                    )
                    repair_actions.append(
                        RepairAction(
                            action="set_value",
                            path=f"simulation_config.monitors.{idx}.size_um",
                            value=correct_size,
                            reason=(
                                f"Swap monitor plane to be perpendicular to "
                                f"{axis}-propagation ({inferred_port})."
                            ),
                        )
                    )


def _validate_boundary(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    boundary = bundle.simulation_config.domain.boundary
    for key, value in boundary.items():
        normalized = str(value).strip().lower()
        if normalized in _ALLOWED_BOUNDARY_TYPES:
            continue
        issues.append(
            ValidationIssue(
                code="invalid_boundary_type",
                path=f"simulation_config.domain.boundary.{key}",
                message=f"Unsupported boundary type `{value}`.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path=f"simulation_config.domain.boundary.{key}",
                value="pml",
                reason="Use a supported boundary type; default to pml.",
            )
        )


def _validate_optimization_variables(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    params = bundle.simulation_config.geometry.parameters
    for idx, variable in enumerate(bundle.optimization_config.variables):
        if variable.name in params:
            continue
        issues.append(
            ValidationIssue(
                code="variable_not_in_geometry",
                path=f"optimization_config.variables.{idx}.name",
                message=f"Variable `{variable.name}` has no matching geometry parameter.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="remove_item",
                path=f"optimization_config.variables.{idx}",
                reason="Remove orphan variable or map it to an existing geometry parameter.",
            )
        )


def _validate_metric_goal_consistency(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    objective = bundle.optimization_config.objective
    metric = str(objective.metric or "").strip().lower()
    expected_goal = _METRIC_GOAL_COMPATIBILITY.get(metric)
    if expected_goal is None:
        return

    current_goal = str(objective.goal or "").strip().lower()
    if current_goal == expected_goal:
        return

    issues.append(
        ValidationIssue(
            code="metric_goal_mismatch",
            path="optimization_config.objective.goal",
            message=(
                f"Objective metric `{objective.metric}` is inconsistent with goal `{objective.goal}`. "
                f"Expected goal: `{expected_goal}`."
            ),
        )
    )
    repair_actions.append(
        RepairAction(
            action="set_value",
            path="optimization_config.objective.goal",
            value=expected_goal,
            reason="Apply metric-goal consistency rule before inverse-design execution.",
        )
    )


def _domain_bounds(size_um: List[float], center_um: List[float]) -> List[Tuple[float, float]]:
    return [
        (center - size / 2, center + size / 2)
        for center, size in zip(center_um, size_um)
    ]


def _point_within_bounds(point: List[float], bounds: List[Tuple[float, float]]) -> bool:
    return all(low <= value <= high for value, (low, high) in zip(point, bounds))


def _clamp_point(point: List[float], bounds: List[Tuple[float, float]]) -> List[float]:
    clamped: List[float] = []
    for value, (low, high) in zip(point, bounds):
        clamped.append(round(min(max(value, low), high), 6))
    return clamped


def _freq_from_wavelength_nm(wavelength_nm: float) -> float:
    return 299_792_458.0 / (wavelength_nm * 1e-9)


def _validate_geometry_semantics(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    params = sim_cfg.geometry.parameters
    domain = sim_cfg.domain

    wg_width = _as_float(params.get("wg_width"))
    wg_height = _as_float(params.get("wg_height"))

    if wg_width is not None and not (0.05 <= wg_width <= 5.0):
        safe_width = round(min(max(wg_width, 0.05), 5.0), 4)
        issues.append(
            ValidationIssue(
                code="invalid_waveguide_width",
                path="simulation_config.geometry.parameters.wg_width",
                message="Waveguide width should stay within a physically reasonable range [0.05, 5.0] um.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.geometry.parameters.wg_width",
                value=safe_width,
                reason="Clamp waveguide width to a physically valid range.",
            )
        )

    if wg_height is not None and not (0.05 <= wg_height <= 2.0):
        safe_height = round(min(max(wg_height, 0.05), 2.0), 4)
        issues.append(
            ValidationIssue(
                code="invalid_waveguide_height",
                path="simulation_config.geometry.parameters.wg_height",
                message="Waveguide height should stay within a physically reasonable range [0.05, 2.0] um.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.geometry.parameters.wg_height",
                value=safe_height,
                reason="Clamp waveguide height to a physically valid range.",
            )
        )

    if wg_height is not None and domain.size_um[2] <= wg_height:
        safe_domain_z = round(max(domain.size_um[2], wg_height + 1.0), 4)
        issues.append(
            ValidationIssue(
                code="insufficient_vertical_domain",
                path="simulation_config.domain.size_um.2",
                message="Simulation domain z-span must be larger than core height.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.domain.size_um.2",
                value=safe_domain_z,
                reason="Increase vertical simulation span to include core and cladding regions.",
            )
        )

    substrate_thickness = _as_float(params.get("substrate_thickness"))
    if substrate_thickness is not None and wg_height is not None and substrate_thickness < wg_height:
        issues.append(
            ValidationIssue(
                code="substrate_thickness_too_small",
                path="simulation_config.geometry.parameters.substrate_thickness",
                message="Substrate thickness should not be smaller than core height.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.geometry.parameters.substrate_thickness",
                value=round(wg_height, 4),
                reason="Set substrate thickness to at least the waveguide core thickness.",
            )
        )

    _validate_domain_padding(bundle, issues, repair_actions)


def _validate_source_monitor_semantics(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    component_type = sim_cfg.component_type
    params = sim_cfg.geometry.parameters
    domain = sim_cfg.domain
    source = sim_cfg.source
    half_x = domain.size_um[0] / 2
    wg_width = _as_float(params.get("wg_width")) or 0.5
    wg_height = _as_float(params.get("wg_height")) or 0.22
    expected_ports = _expected_output_port_positions(
        component_type,
        sim_cfg.geometry.parameters,
        sim_cfg.domain.size_um,
    )
    source_port = str(getattr(source, "port", "") or "port_o1").strip().lower() or "port_o1"
    expected_source_xy = expected_ports.get(source_port) or expected_ports.get("port_o1")
    if expected_source_xy is None:
        expected_source_xy = (-half_x + 1.0, 0.0)

    expected_direction = _default_source_direction_for_port(
        component_type=component_type,
        port_name=source_port,
        port_xy=expected_source_xy,
    )
    if source.direction != expected_direction:
        issues.append(
            ValidationIssue(
                code="source_direction_mismatch",
                path="simulation_config.source.direction",
                message="Source direction is inconsistent with the selected source port.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.source.direction",
                value=expected_direction,
                reason="Align source direction with the selected source-port orientation.",
            )
        )

    expected_axis = _port_prop_axis(component_type, source_port)
    corridor_tol = max(wg_width * 2.0, 1.5)
    if expected_axis == "y":
        primary_offset = abs(float(source.center_um[1]) - float(expected_source_xy[1]))
        cross_offset = abs(float(source.center_um[0]) - float(expected_source_xy[0]))
    else:
        primary_offset = abs(float(source.center_um[0]) - float(expected_source_xy[0]))
        cross_offset = abs(float(source.center_um[1]) - float(expected_source_xy[1]))

    if primary_offset > 3.0:
        issues.append(
            ValidationIssue(
                code="source_not_near_input_port",
                path="simulation_config.source.center_um",
                message="Source should be placed near the selected source port.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.source.center_um",
                value=[
                    round(float(expected_source_xy[0]), 6),
                    round(float(expected_source_xy[1]), 6),
                    round(wg_height / 2, 6),
                ],
                reason="Move source to the selected source-port neighborhood.",
            )
        )

    if cross_offset > corridor_tol:
        issues.append(
            ValidationIssue(
                code="source_lateral_misalignment",
                path="simulation_config.source.center_um.1",
                message="Source lateral offset is too far from the expected source-port corridor.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.source.center_um.1",
                value=round(float(expected_source_xy[1]), 6),
                reason="Recenter source laterally around the selected source port.",
            )
        )

    if abs(source.center_um[2] - wg_height / 2) > max(wg_height, 0.2):
        issues.append(
            ValidationIssue(
                code="source_vertical_misalignment",
                path="simulation_config.source.center_um.2",
                message="Source z-position should align with the core center plane.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.source.center_um.2",
                value=round(wg_height / 2, 6),
                reason="Align source vertically to the nominal waveguide core center.",
            )
        )

    flux_and_mode = [
        m for m in sim_cfg.monitors
        if m.monitor_type in {"flux", "mode"}
    ]
    exp_o2 = expected_ports.get("port_o2", (half_x - 1.0, 0.0))
    has_output_monitor = any(
        abs(float(m.center_um[0]) - float(exp_o2[0])) <= 3.0 and abs(float(m.center_um[1]) - float(exp_o2[1])) <= 1.5
        for m in flux_and_mode
    ) or any(m.center_um[0] >= (half_x - 1.5) for m in flux_and_mode)
    if not has_output_monitor:
        out_axis = _port_prop_axis(component_type, "port_o2")
        out_size = list(monitor_size_for_port(out_axis, wg_width, wg_height))
        issues.append(
            ValidationIssue(
                code="missing_output_aligned_monitor",
                path="simulation_config.monitors",
                message="At least one flux/mode monitor should be near the output-side boundary.",
            )
        )
        repair_actions.append(
            RepairAction(
                action="add_item",
                path="simulation_config.monitors",
                value={
                    "name": "output_flux",
                    "monitor_type": "flux",
                    "center_um": [round(float(exp_o2[0]), 6), round(float(exp_o2[1]), 6), round(wg_height / 2, 6)],
                    "size_um": out_size,
                    "freqs_hz": [_freq_from_wavelength_nm(sim_cfg.wavelength_nm)],
                    "metric": "transmission",
                },
                reason="Add an output-aligned monitor for transmission objective evaluation.",
            )
        )


def _validate_device_topology_priors(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    component_type = sim_cfg.component_type
    flux_monitors = [m for m in sim_cfg.monitors if m.monitor_type == "flux"]
    objective_metric = str(bundle.optimization_config.objective.metric or "").strip().lower()

    if component_type == "crossing":
        requires_cross_channel_observability = objective_metric in {"crosstalk", "cross_talk", "secondary_output"}
        if not requires_cross_channel_observability:
            return
        has_vertical_tap = any(abs(m.center_um[1]) > 0.5 for m in flux_monitors)
        if len(flux_monitors) < 2 or not has_vertical_tap:
            issues.append(
                ValidationIssue(
                    code="crossing_topology_monitor_insufficient",
                    path="simulation_config.monitors",
                    message="Crossing simulations should include through and cross-port flux monitors.",
                )
            )
            repair_actions.append(
                RepairAction(
                    action="add_item",
                    path="simulation_config.monitors",
                    value={
                        "name": "cross_flux",
                        "monitor_type": "flux",
                        "center_um": [0.0, 1.25, 0.11],
                        "size_um": [1.5, 0.0, 1.0],
                        "freqs_hz": [_freq_from_wavelength_nm(sim_cfg.wavelength_nm)],
                        "metric": "crosstalk",
                    },
                    reason="Add orthogonal-port monitor for crossing topology observability.",
                )
            )

    if component_type in {"y_branch", "mmi", "splitter", "mzi", "directional_coupler"} and len(flux_monitors) < 2:
        issues.append(
            ValidationIssue(
                code="multiport_topology_monitor_insufficient",
                path="simulation_config.monitors",
                message="Multi-port split devices should include at least two output flux monitors.",
                severity="warning",
            )
        )

    # Demux-oriented monitor placement must align with component output ports.
    if objective_metric in {"demux_routing", "mux_routing", "crosstalk", "secondary_output"} and component_type in {
        "mmi",
        "splitter",
        "y_branch",
        "directional_coupler",
    }:
        expected = _expected_output_port_positions(component_type, sim_cfg.geometry.parameters, sim_cfg.domain.size_um)
        wg_height = _as_float(sim_cfg.geometry.parameters.get("wg_height")) or 0.22
        tolerance_um = 0.4

        for idx, monitor in enumerate(sim_cfg.monitors):
            expected_port = None
            monitor_name = str(monitor.name).strip().lower()
            if monitor_name in {"through_flux", "mode_monitor"}:
                expected_port = "port_o2"
            elif monitor_name == "secondary_flux":
                expected_port = "port_o3"
            else:
                parsed = _extract_port_name_from_monitor_name(monitor_name)
                if parsed:
                    expected_port = parsed

            if expected_port is None or expected_port not in expected:
                continue

            exp_x, exp_y = expected[expected_port]
            x_err = abs(float(monitor.center_um[0]) - exp_x)
            y_err = abs(float(monitor.center_um[1]) - exp_y)
            if x_err <= tolerance_um and y_err <= tolerance_um:
                continue

            issues.append(
                ValidationIssue(
                    code="monitor_port_alignment_mismatch",
                    path=f"simulation_config.monitors.{idx}.center_um",
                    message=(
                        f"Monitor `{monitor.name}` is not aligned with {expected_port}. "
                        f"Expected approx ({exp_x:.3f}, {exp_y:.3f}), got ({monitor.center_um[0]:.3f}, {monitor.center_um[1]:.3f})."
                    ),
                    severity="warning",
                )
            )
            repair_actions.append(
                RepairAction(
                    action="set_value",
                    path=f"simulation_config.monitors.{idx}.center_um",
                    value=[round(exp_x, 6), round(exp_y, 6), round(wg_height / 2, 6)],
                    reason="Align monitor center to component output port geometry for demux observability.",
                )
            )

        # For mode-demux semantics, each target output port must have a
        # dedicated ModeMonitor (e.g. mode_port_o2, mode_port_o3).
        required_mode_ports: List[str] = []
        for case in bundle.optimization_config.objective_cases:
            port = str(getattr(case, "target_port", "") or "").strip().lower()
            if port.startswith("port_o") and port not in required_mode_ports:
                required_mode_ports.append(port)

        existing_mode_ports: set[str] = set()
        for monitor in sim_cfg.monitors:
            if monitor.monitor_type != "mode":
                continue
            name = str(monitor.name).strip().lower()
            if name == "mode_monitor":
                existing_mode_ports.add("port_o2")
                continue
            if name.startswith("mode_port_o"):
                existing_mode_ports.add("port_" + name.split("mode_", 1)[-1].split("port_", 1)[-1])

        existing_field_ports: set[str] = set()
        for monitor in sim_cfg.monitors:
            if monitor.monitor_type != "field":
                continue
            name = str(monitor.name).strip().lower()
            if name.startswith("field_port_o"):
                existing_field_ports.add("port_" + name.split("field_", 1)[-1].split("port_", 1)[-1])

        wg_width = _as_float(sim_cfg.geometry.parameters.get("wg_width")) or 0.5
        for port in required_mode_ports:
            if port in existing_mode_ports:
                pass
            elif port in expected:
                exp_x, exp_y = expected[port]
                axis = _port_prop_axis(component_type, port)
                port_width = _waveguide_width_for_port(
                    component_type=component_type,
                    params=sim_cfg.geometry.parameters,
                    port_name=port,
                    objective_metric=objective_metric,
                )
                mode_size = list(monitor_size_for_port(axis, port_width, wg_height))
                issues.append(
                    ValidationIssue(
                        code="demux_mode_monitor_missing",
                        path="simulation_config.monitors",
                        message=(
                            f"Missing mode monitor for target output `{port}`. "
                            "Mode-demux objectives require per-port ModeMonitor observability."
                        ),
                        severity="warning",
                    )
                )
                repair_actions.append(
                    RepairAction(
                        action="add_item",
                        path="simulation_config.monitors",
                        value={
                            "name": f"mode_{port}",
                            "monitor_type": "mode",
                            "center_um": [round(exp_x, 6), round(exp_y, 6), round(wg_height / 2, 6)],
                            "size_um": mode_size,
                            "freqs_hz": [_freq_from_wavelength_nm(sim_cfg.wavelength_nm)],
                            "metric": "mode_overlap",
                        },
                        reason="Add per-target mode monitor for mode-demux objective validation.",
                    )
                )

            if port in existing_field_ports:
                continue
            if port not in expected:
                continue
            exp_x, exp_y = expected[port]
            axis = _port_prop_axis(component_type, port)
            port_width = _waveguide_width_for_port(
                component_type=component_type,
                params=sim_cfg.geometry.parameters,
                port_name=port,
                objective_metric=objective_metric,
            )
            field_size = list(monitor_size_for_port(axis, port_width, wg_height))
            issues.append(
                ValidationIssue(
                    code="demux_field_monitor_missing",
                    path="simulation_config.monitors",
                    message=(
                        f"Missing field monitor for target output `{port}`. "
                        "Mode-demux objectives require per-port field observability."
                    ),
                    severity="warning",
                )
            )
            repair_actions.append(
                RepairAction(
                    action="add_item",
                    path="simulation_config.monitors",
                    value={
                        "name": f"field_{port}",
                        "monitor_type": "field",
                        "center_um": [round(exp_x, 6), round(exp_y, 6), round(wg_height / 2, 6)],
                        "size_um": field_size,
                        "freqs_hz": [_freq_from_wavelength_nm(sim_cfg.wavelength_nm)],
                        "field_component": "Ey",
                    },
                    reason="Add per-target field monitor for mode-demux output-port visualization.",
                )
            )


def _expected_output_port_positions(
    component_type: str,
    params: Dict[str, Any],
    domain_size: List[float],
) -> Dict[str, Tuple[float, float]]:
    fallback_x = float(domain_size[0]) / 2 - 1.0
    mapping: Dict[str, Tuple[float, float]] = {
        "port_o1": (-float(domain_size[0]) / 2 + 1.0, 0.0),
        "port_o2": (fallback_x, 0.0),
    }

    if component_type in {"mmi", "splitter"}:
        mmi_width = _as_float(params.get("mmi_width")) or 2.5
        mmi_length = _as_float(params.get("mmi_length")) or 10.0
        num_outputs = int(round(_as_float(params.get("mmi_num_outputs")) or 2))
        x_in = -mmi_length / 2.0 - 9.0
        x_out = mmi_length / 2.0 + 9.0
        spacing = mmi_width / (num_outputs + 1)
        mapping["port_o1"] = (x_in, 0.0)
        for i in range(num_outputs):
            port_key = f"port_o{i + 2}"
            y_pos = -mmi_width / 2.0 + spacing * (i + 1)
            mapping[port_key] = (x_out, round(y_pos, 6))
    elif component_type == "y_branch":
        arm_length = _as_float(params.get("arm_length")) or 15.0
        arm_separation = _as_float(params.get("arm_separation")) or 3.0
        x_in = -arm_length - 9.0
        x_out = arm_length + 9.0
        mapping["port_o1"] = (x_in, 0.0)
        mapping["port_o2"] = (x_out, arm_separation / 2.0)
        mapping["port_o3"] = (x_out, -arm_separation / 2.0)
    elif component_type == "directional_coupler":
        coupler_length = _as_float(params.get("coupler_length")) or 10.0
        gap = _as_float(params.get("gap")) or 0.2
        wg_width = _as_float(params.get("wg_width")) or 0.5
        x_in = -coupler_length / 2.0 - 9.0
        x_out = coupler_length / 2.0 + 9.0
        y_upper = gap / 2.0 + wg_width / 2.0
        y_lower = -y_upper
        mapping["port_o1"] = (x_in, y_upper)
        mapping["port_o2"] = (x_out, y_upper)
        mapping["port_o3"] = (x_out, y_lower)
        mapping["port_o4"] = (x_in, y_lower)

    return mapping


def _extract_port_name_from_monitor_name(name: str) -> str:
    lowered = str(name or "").strip().lower()
    match = re.search(r"port_o(\d+)", lowered)
    if not match:
        return ""
    try:
        return f"port_o{int(match.group(1))}"
    except ValueError:
        return ""


def _waveguide_width_for_port(
    *,
    component_type: str,
    params: Dict[str, Any],
    port_name: str,
    objective_metric: str,
) -> float:
    default_width = _as_float(params.get("wg_width")) or 0.5
    metric = str(objective_metric or "").strip().lower()
    lowered_port = str(port_name or "").strip().lower()
    explicit_o1 = _as_float(params.get("port_o1_wg_width"))
    explicit_side = _as_float(params.get("side_port_wg_width"))
    if lowered_port == "port_o1" and explicit_o1 is not None:
        return max(float(explicit_o1), 1e-3)
    if lowered_port != "port_o1" and explicit_side is not None:
        return max(float(explicit_side), 1e-3)
    if component_type in {"mmi", "splitter"} and metric == "mux_routing" and lowered_port == "port_o1":
        mmi_width = _as_float(params.get("mmi_width")) or 2.5
        candidate = max(default_width * 2.0, 1.0)
        upper = max(default_width + 0.05, mmi_width - 0.2)
        return min(candidate, upper)
    return default_width


def _validate_mesh_and_spectral_semantics(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    domain = sim_cfg.domain
    source = sim_cfg.source
    min_run_time_s = _recommended_min_run_time_s(domain.size_um, source.wavelength_nm, source.bandwidth_nm)

    if sim_cfg.run_time_s < min_run_time_s:
        issues.append(
            ValidationIssue(
                code="insufficient_run_time",
                path="simulation_config.run_time_s",
                message=(
                    "Run time is too short for reliable decay to near-zero fields. "
                    "Increase run_time or rely on shutoff only after a sufficient minimum horizon."
                ),
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.run_time_s",
                value=min_run_time_s,
                reason="Use a domain-and-source-based minimum run time following Tidy3D FAQ guidance.",
            )
        )

    if sim_cfg.shutoff == 0:
        issues.append(
            ValidationIssue(
                code="shutoff_disabled",
                path="simulation_config.shutoff",
                message="shutoff=0 disables early termination and may cause unnecessary simulation cost.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.shutoff",
                value=1e-5,
                reason="Restore Tidy3D-style default shutoff threshold for efficient and stable termination.",
            )
        )
    elif sim_cfg.shutoff > _MAX_SHUTOFF_FOR_ACCURACY:
        issues.append(
            ValidationIssue(
                code="shutoff_too_large",
                path="simulation_config.shutoff",
                message="Large shutoff can terminate too early and degrade frequency-domain accuracy.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.shutoff",
                value=1e-5,
                reason="Use a conservative shutoff threshold to avoid premature termination.",
            )
        )

    if domain.min_steps_per_wvl < _MIN_STEPS_PER_WAVELENGTH_RECOMMENDED:
        issues.append(
            ValidationIssue(
                code="coarse_mesh_recommendation",
                path="simulation_config.domain.min_steps_per_wvl",
                message="Tidy3D AutoGrid guidance suggests starting from at least 10 steps per wavelength.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.domain.min_steps_per_wvl",
                value=_MIN_STEPS_PER_WAVELENGTH_RECOMMENDED,
                reason="Raise mesh resolution to the recommended AutoGrid baseline.",
            )
        )

    freq0 = _freq_from_wavelength_nm(source.wavelength_nm)
    wl_um = source.wavelength_nm * 1e-3
    bw_um = source.bandwidth_nm * 1e-3
    wl_min = max(wl_um - bw_um / 2, 1e-6)
    wl_max = wl_um + bw_um / 2
    freq_min = _LIGHT_SPEED_M_PER_S / (wl_max * 1e-6)
    freq_max = _LIGHT_SPEED_M_PER_S / (wl_min * 1e-6)

    for idx, monitor in enumerate(sim_cfg.monitors):
        for freq in monitor.freqs_hz:
            if freq_min <= freq <= freq_max:
                continue
            issues.append(
                ValidationIssue(
                    code="monitor_frequency_outside_source_band",
                    path=f"simulation_config.monitors.{idx}.freqs_hz",
                    message="Monitor frequency lies outside the source excitation bandwidth.",
                    severity="warning",
                )
            )
            repair_actions.append(
                RepairAction(
                    action="set_value",
                    path=f"simulation_config.monitors.{idx}.freqs_hz",
                    value=[freq0],
                    reason="Align monitor sampling with source center frequency for stable objective reading.",
                )
            )
            break


def _validate_domain_padding(
    bundle: InverseDesignConfigBundle,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    sim_cfg = bundle.simulation_config
    domain = sim_cfg.domain
    half_domain = [value / 2 for value in domain.size_um]
    half_extent = _estimate_geometry_half_extent(sim_cfg.component_type, sim_cfg.geometry.parameters)
    pml_buffer_um = 0.5 * (sim_cfg.wavelength_nm * 1e-3)

    for axis, (half_d, half_e) in enumerate(zip(half_domain, half_extent)):
        needs_pml_margin = _axis_uses_pml(domain.boundary, axis)
        clearance = half_d - half_e
        if not needs_pml_margin:
            continue
        if clearance >= pml_buffer_um:
            continue

        axis_label = ("x", "y", "z")[axis]
        safe_span = round(max(domain.size_um[axis], 2 * (half_e + pml_buffer_um)), 6)
        issues.append(
            ValidationIssue(
                code="insufficient_pml_clearance",
                path=f"simulation_config.domain.size_um.{axis}",
                message=(
                    "Geometry should stay at least half a wavelength away from absorbing layers "
                    "to reduce evanescent-field coupling into PML."
                ),
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path=f"simulation_config.domain.size_um.{axis}",
                value=safe_span,
                reason=f"Increase {axis_label}-span to satisfy minimum PML clearance.",
            )
        )


def _estimate_geometry_half_extent(component_type: str, params: Dict[str, Any]) -> List[float]:
    wg_width = _as_float(params.get("wg_width")) or 0.5
    wg_height = _as_float(params.get("wg_height")) or 0.22

    if component_type == "waveguide":
        half_x = (_as_float(params.get("wg_length")) or 10.0) / 2
        half_y = wg_width / 2
    elif component_type == "crossing":
        arm = (_as_float(params.get("wg_length")) or 10.0) / 2
        half_x = arm
        half_y = arm
    elif component_type == "ring_resonator":
        radius = _as_float(params.get("ring_radius")) or 5.0
        half_x = radius + wg_width
        half_y = radius + wg_width
    elif component_type in {"mmi", "splitter"}:
        half_x = (_as_float(params.get("mmi_length")) or 10.0) / 2
        half_y = (_as_float(params.get("mmi_width")) or 2.5) / 2
    elif component_type in {"y_branch", "mzi"}:
        half_x = (_as_float(params.get("arm_length")) or 15.0) / 2
        half_y = (_as_float(params.get("arm_separation")) or 3.0) / 2 + wg_width
    elif component_type == "directional_coupler":
        half_x = (_as_float(params.get("coupler_length")) or 10.0) / 2
        half_y = (_as_float(params.get("gap")) or 0.2) / 2 + wg_width
    else:
        half_x = (_as_float(params.get("wg_length")) or 10.0) / 2
        half_y = wg_width

    half_z = max(wg_height / 2, 0.11)
    return [half_x, half_y, half_z]


def _axis_uses_pml(boundary: Dict[str, str], axis_index: int) -> bool:
    axis = ("x", "y", "z")[axis_index]
    minus = str(boundary.get(f"{axis}_min", "")).strip().lower()
    plus = str(boundary.get(f"{axis}_max", "")).strip().lower()
    return minus == "pml" or plus == "pml"


def _as_float(value: Any) -> float | None:
    if isinstance(value, (int, float)):
        return float(value)
    return None


def _recommended_min_run_time_s(domain_size_um: List[float], wavelength_nm: float, bandwidth_nm: float) -> float:
    largest_dim_m = max(domain_size_um) * 1e-6
    propagation_time_s = 3.0 * largest_dim_m * _DEFAULT_GROUP_INDEX / _LIGHT_SPEED_M_PER_S

    wl_um = wavelength_nm * 1e-3
    bw_um = max(bandwidth_nm * 1e-3, 1e-6)
    wl_min = max(wl_um - bw_um / 2, 1e-6)
    wl_max = wl_um + bw_um / 2
    fwidth = 0.5 * (_LIGHT_SPEED_M_PER_S / (wl_min * 1e-6) - _LIGHT_SPEED_M_PER_S / (wl_max * 1e-6))
    source_tail_s = 2.0 / max(fwidth, 1e9)

    return round(max(propagation_time_s + source_tail_s, 1e-13), 15)


def _fetch_mcp_evidence_for_step4(
    bundle: InverseDesignConfigBundle,
    deterministic_issues: List[ValidationIssue],
    memory_store: InverseDesignWorkingMemory,
    *,
    search_fn: Any | None = None,
    fetch_fn: Any | None = None,
) -> str:
    """Query MCP for step4-specific validation evidence.

    Returns formatted documentation text to inject into the LLM reviewer prompt.
    Records MCP usage/failure in working memory.
    """
    if search_fn is None or fetch_fn is None:
        from PhotonicsAI.tools.tidy3d_tools import fetch_tidy3d_doc, search_tidy3d_docs
        if search_fn is None:
            search_fn = search_tidy3d_docs
        if fetch_fn is None:
            fetch_fn = fetch_tidy3d_doc

    component_type = bundle.simulation_config.component_type or "photonic device"
    queries = [
        f"Tidy3D {component_type} simulation validation best practices",
    ]
    objective_metric = str(bundle.optimization_config.objective.metric or "").strip().lower()
    if objective_metric == "demux_routing":
        queries.extend(
            [
                "Tidy3D AdjointPlugin9WDM notebook",
                "Tidy3D MultiplexingMMI notebook",
                f"Tidy3D {component_type} monitor placement port_o2 port_o3",
            ]
        )
    # Add issue-targeted queries for specific validation problems.
    issue_codes = {iss.code for iss in deterministic_issues}
    if any("boundary" in c for c in issue_codes):
        queries.append(f"Tidy3D boundary condition PML {component_type}")
    if any("monitor" in c for c in issue_codes):
        queries.append(f"Tidy3D monitor placement flux mode {component_type}")
    if any("mesh" in c or "spectral" in c for c in issue_codes):
        queries.append("Tidy3D mesh resolution min_steps_per_wavelength")

    evidence_parts: List[str] = []
    mcp_urls: List[str] = []
    mcp_errors: List[str] = []

    for query in queries:
        try:
            search_result = search_fn(query=query, max_results=2)
            if not search_result.get("ok"):
                mcp_errors.append(f"MCP search returned ok=False for: {query}")
                continue
            for raw_hit in search_result.get("data", {}).get("results", []):
                url = str(raw_hit.get("url", "")).strip()
                if not url or url in mcp_urls:
                    continue
                try:
                    fetch_result = fetch_fn(url=url)
                    if not fetch_result.get("ok"):
                        continue
                    content = str(fetch_result.get("data", {}).get("content", "")).strip()
                    if content:
                        evidence_parts.append(f"[MCP Doc: {url}]\n{content[:2000]}")
                        mcp_urls.append(url)
                except Exception as fetch_exc:
                    mcp_errors.append(f"MCP fetch failed for {url}: {fetch_exc}")
        except Exception as search_exc:
            mcp_errors.append(f"MCP search error for '{query}': {search_exc}")

    # Surface doc references already embedded in the config bundle.
    for ref in bundle.simulation_config.doc_references:
        ref_url = ref.url if hasattr(ref, "url") else str(ref)
        ref_summary = ref.summary if hasattr(ref, "summary") else ""
        if ref_summary:
            evidence_parts.append(f"[Config Doc: {ref_url}]\nSummary: {ref_summary}")

    if mcp_errors:
        memory_store.record(
            stage="step4_mcp",
            key=component_type,
            summary=f"Step4 MCP evidence retrieval had {len(mcp_errors)} errors, {len(mcp_urls)} docs retrieved.",
            issues=mcp_errors,
            evidence_urls=mcp_urls,
            metadata={"queries": queries, "path": "mcp_pre_fetch"},
        )

    if mcp_urls:
        memory_store.record(
            stage="step4_mcp",
            key=component_type,
            summary=f"Step4 MCP retrieved {len(mcp_urls)} docs for LLM reviewer enrichment.",
            evidence_urls=mcp_urls,
            metadata={"queries": queries, "path": "mcp_main"},
        )

    return "\n\n".join(evidence_parts)


def _run_non_blocking_llm_review(
    bundle: InverseDesignConfigBundle,
    *,
    deterministic_issues: List[ValidationIssue],
    deterministic_actions: List[RepairAction],
    constraint_packet: Step4ConstraintPacket | None,
    llm_call_fn: LLMCallFn | None,
    llm_model: str,
    memory_store: InverseDesignWorkingMemory,
    search_fn: Any | None = None,
    fetch_fn: Any | None = None,
) -> LLMReviewResult:
    caller = llm_call_fn or _default_llm_call
    if caller is None:
        return LLMReviewResult()

    # --- MCP evidence retrieval (pre-fetch + inject) ---
    mcp_evidence = _fetch_mcp_evidence_for_step4(
        bundle, deterministic_issues, memory_store,
        search_fn=search_fn, fetch_fn=fetch_fn,
    )

    prompt_parts = [
        "Review this inverse-design configuration and deterministic validation output. "
        "Return strict JSON: {\"review_notes\": [string], \"repair_actions\": [RepairAction]}.",
        f"Config JSON: {bundle.model_dump_json()}",
        f"Step4 RAG constraint packet: {json.dumps(constraint_packet.model_dump() if constraint_packet else {}, ensure_ascii=True)}",
        f"Deterministic issues: {json.dumps([item.model_dump() for item in deterministic_issues], ensure_ascii=True)}",
        f"Deterministic repairs: {json.dumps([item.model_dump() for item in deterministic_actions], ensure_ascii=True)}",
    ]
    if mcp_evidence:
        prompt_parts.append(
            "The following Tidy3D documentation evidence was retrieved via MCP. "
            "Use it to inform your validation review:\n" + mcp_evidence
        )
    prompt = "\n".join(prompt_parts)

    sys_prompt = (
        "You are a non-blocking Step4 reviewer. "
        "Do not repeat deterministic errors unless you provide a new actionable repair path. "
        "Return JSON only."
    )

    try:
        raw = caller(prompt, sys_prompt, llm_model)
        payload = _extract_json_object(str(raw))
        review = LLMReviewResult.model_validate(payload)
    except Exception as exc:
        memory_store.record(
            stage="step4_review",
            key=bundle.simulation_config.component_type,
            summary="Step4 non-blocking LLM reviewer failed; deterministic result retained.",
            issues=[str(exc)],
            metadata={
                "fallback": "deterministic_validation_only",
                "mcp_evidence_available": bool(mcp_evidence),
            },
        )
        return LLMReviewResult()

    if review.review_notes or review.repair_actions:
        memory_store.record(
            stage="step4_review",
            key=bundle.simulation_config.component_type,
            summary="Step4 non-blocking reviewer produced additional insights.",
            proposed_fixes=[action.path for action in review.repair_actions],
            metadata={"notes": review.review_notes, "mcp_evidence_used": bool(mcp_evidence)},
        )
    return review


def _review_enabled(include_llm_review: bool | None) -> bool:
    if include_llm_review is not None:
        return include_llm_review
    value = os.getenv("INVERSE_DESIGN_ENABLE_LLM_REVIEW", "0").strip().lower()
    return value in {"1", "true", "yes", "on"}


def _default_llm_call(prompt: str, sys_prompt: str, llm_model: str) -> str:
    from PhotonicsAI.Photon.llm_api import call_llm

    return call_llm(prompt, sys_prompt, llm_api_selection=llm_model)


def _extract_json_object(text: str) -> Dict[str, Any]:
    candidate = text.strip()
    if candidate.startswith("```"):
        lines = candidate.splitlines()
        if len(lines) >= 3:
            candidate = "\n".join(lines[1:-1])
    match = re.search(r"\{[\s\S]*\}", candidate)
    if match:
        candidate = match.group(0)
    return json.loads(candidate)


def _coerce_constraint_packet(
    packet: Step4ConstraintPacket | Dict[str, Any] | None,
) -> Step4ConstraintPacket | None:
    if packet is None:
        return None
    if isinstance(packet, Step4ConstraintPacket):
        return packet
    return Step4ConstraintPacket.model_validate(packet)


def _validate_rag_constraint_packet(
    bundle: InverseDesignConfigBundle,
    packet: Step4ConstraintPacket,
    issues: List[ValidationIssue],
    repair_actions: List[RepairAction],
) -> None:
    boundary = bundle.simulation_config.domain.boundary
    expected_boundary = packet.required_boundary.strip().lower()
    if expected_boundary in _ALLOWED_BOUNDARY_TYPES:
        mismatched = [
            key for key, value in boundary.items() if str(value).strip().lower() != expected_boundary
        ]
        if mismatched:
            issues.append(
                ValidationIssue(
                    code="rag_boundary_mismatch",
                    path="simulation_config.domain.boundary",
                    message=(
                        f"Step4 RAG requires `{expected_boundary}` boundaries; "
                        f"mismatched axes: {', '.join(mismatched)}."
                    ),
                    severity="warning",
                )
            )
            repair_actions.append(
                RepairAction(
                    action="set_value",
                    path="simulation_config.domain.boundary",
                    value={
                        "x_min": expected_boundary,
                        "x_max": expected_boundary,
                        "y_min": expected_boundary,
                        "y_max": expected_boundary,
                        "z_min": expected_boundary,
                        "z_max": expected_boundary,
                    },
                    reason="Align boundary settings with Step4 RAG hard constraint packet.",
                )
            )

    existing_monitor_types = {
        monitor.monitor_type for monitor in bundle.simulation_config.monitors
    }
    missing_monitor_types = [
        monitor_type
        for monitor_type in packet.required_monitor_types
        if monitor_type not in existing_monitor_types
    ]
    if missing_monitor_types:
        issues.append(
            ValidationIssue(
                code="rag_monitor_coverage_missing",
                path="simulation_config.monitors",
                message=(
                    "Step4 RAG requires monitor coverage for: "
                    f"{', '.join(missing_monitor_types)}."
                ),
                severity="error",
            )
        )
        for monitor_type in missing_monitor_types:
            repair_actions.append(
                RepairAction(
                    action="add_item",
                    path="simulation_config.monitors",
                    value=_default_monitor_for_type(bundle, monitor_type),
                    reason=(
                        "Add required monitor type from Step4 RAG hard constraint packet "
                        f"({monitor_type})."
                    ),
                )
            )

    mesh_floor = max(10, int(packet.min_steps_per_wvl))
    if bundle.simulation_config.domain.min_steps_per_wvl < mesh_floor:
        issues.append(
            ValidationIssue(
                code="rag_mesh_floor_violation",
                path="simulation_config.domain.min_steps_per_wvl",
                message=f"Step4 RAG requires min_steps_per_wvl >= {mesh_floor}.",
                severity="warning",
            )
        )
        repair_actions.append(
            RepairAction(
                action="set_value",
                path="simulation_config.domain.min_steps_per_wvl",
                value=mesh_floor,
                reason="Apply mesh floor from Step4 RAG hard constraint packet.",
            )
        )


def _default_monitor_for_type(bundle: InverseDesignConfigBundle, monitor_type: str) -> Dict[str, Any]:
    domain = bundle.simulation_config.domain
    center_x = float(domain.center_um[0]) + float(domain.size_um[0]) / 2 - 1.0
    freq0 = _LIGHT_SPEED_M_PER_S / (float(bundle.simulation_config.wavelength_nm) * 1e-9)
    base = {
        "name": f"rag_{monitor_type}_monitor",
        "monitor_type": monitor_type,
        "center_um": [center_x, 0.0, 0.11],
        "size_um": [0.0, 1.5, 1.0],
        "freqs_hz": [freq0],
    }
    if monitor_type == "field":
        base["field_component"] = "Ey"
    else:
        base["metric"] = "transmission"
    return base
